language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
script:
- mvn test
- mvn jacoco:report
- mvn coveralls:report -DrepoToken="${COVERALLS_TOKEN}"
install:
- export SOURCE=`pwd`
before_deploy:
- mvn clean package
- mkdir releases
- mv $SOURCE/plum-mesh-discovery-core/target/*.jar releases/
- mv $SOURCE/plum-mesh-discovery-etcd/target/*.jar releases/
- mv $SOURCE/plum-mesh-discovery-zk/target/*.jar releases/
- mv $SOURCE/plum-mesh-discovery-start/target/*.jar releases/
- mv $SOURCE/plum-mesh-transport/target/*.jar releases/
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip-cleanup: true
  file_glob: true
  file: "$SOURCE/releases/*"
  on:
    tags: true
